version: '3'
services:
  tvshows-db:
    image: mysql/mysql-server:5.7
    container_name: tvshows-database
    restart: always
    ports:
      - "3313:3306"
    environment:
      MYSQL_DATABASE: tvshowsdb
      MYSQL_USER: user
      MYSQL_PASSWORD: tvshows123
    volumes:
      - ./database/local:/var/lib/mysql
